version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: chatbot_postgres
    environment:
      POSTGRES_DB: chatbot_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      default:
        aliases:
          - db

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      default:
        aliases:
          - adminer

volumes:
  postgres_data: